export const PATHS = {
  HOME: "/",
  ABOUT: "/about",
  CONTACT: "/contact",
  LOGIN: "/login",
  REGISTER: "/register",
  UNAUTHORIZED: "/unauthorized",
  SERVICES: "/services",
  DASHBOARD: "/dashboard",
  ACCOUNT: "/account",
  PROFILE: "/profile",
  USERS: "/users",
  USERS_ADD: "/users/add",
  USERS_EDIT: (id: string | number) => `/users/${id}/edit`,
  PATIENTS: "/patients",
  PATIENTS_ADD: "/patients/add",
  PATIENTS_EDIT: (id: string | number) => `/patients/${id}/edit`,
  PATIENTS_PROFILE: (id: string | number) => `/patients/${id}/profile`,
  PATIENTS_SCHEDULE: `/patients/schedule`,
  DOCTORS: "/doctors",
  DOCTORS_ADD: "/doctors/add",
  DOCTORS_EDIT: (id: string | number) => `/doctors/${id}/edit`,
  DOCTORS_PROFILE: (id: string | number) => `/doctors/${id}/profile`,
  DOCTORS_SCHEDULE: (id: string | number) => `/doctors/${id}/schedule`,
  DOCTORS_SCHEDULE_ADD: (doctorId: string | number) =>
    `/doctors/${doctorId}/schedule/add`,
  DOCTORS_SCHEDULE_EDIT: (
    doctorId: string | number,
    scheduleId: string | number
  ) => `/doctors/${doctorId}/schedule/${scheduleId}/edit`,
  DOCTORS_MY_APPOINTMENTS: `/doctors/appointments`,
  DOCTORS_MY_SCHEDULE: `/doctors/schedule`,
  APPOINTMENTS: "/appointments",
  APPOINTMENTS_ADD: "/appointments/add",
  APPOINTMENTS_EDIT: (id: string | number) => `/appointments/${id}/edit`,
  APPOINTMENTS_DETAILS: (id: string | number) => `/appointments/${id}/details`,
  APPOINTMENTS_DETAILS_EDIT: (id: string | number) =>
    `/appointments/${id}/details/edit`,
  APPOINTMENT_STATUSES: "/appointment-statuses",
  APPOINTMENT_STATUSES_ADD: "/appointment-statuses/add",
  APPOINTMENT_STATUSES_EDIT: (id: string | number) =>
    `/appointment-statuses/${id}/edit`,
  APPOINTMENT_TYPES: "/appointment-types",
  APPOINTMENT_TYPES_ADD: "/appointment-types/add",
  APPOINTMENT_TYPES_EDIT: (id: string | number) =>
    `/appointment-types/${id}/edit`,
  SETTINGS: "/settings",
  SETTINGS_ADD: "/settings/add",
  SETTINGS_EDIT: (id: string | number) => `/settings/${id}/edit`,
  DEPARTMENTS: "/departments",
  DEPARTMENTS_ADD: "/departments/add",
  DEPARTMENTS_EDIT: (id: string | number) => `/departments/${id}/edit`,
  SPECIALIZATIONS: "/specializations",
  SPECIALIZATIONS_ADD: "/specializations/add",
  SPECIALIZATIONS_EDIT: (id: string | number) => `/specializations/${id}/edit`,
  ROLES: "/roles",
  ROLES_ADD: "/roles/add",
  DISCOUNTS: "/discount",
  DISCOUNTS_ADD: "/discount/add",
  DOCS_TEMPLATES: "/docs-templates",
  DOCS_TEMPLATES_ADD: "/docs-templates/add",
  DOCS_TEMPLATES_EDIT: (id: string | number) => `/docs-templates/${id}/edit`,
  PRICELISTS: "/pricelists",
  PRICELISTS_ADD: "/pricelists/add",
  PRICELISTS_EDIT: (id: string | number) => `/pricelists/${id}/edit`,
  PAYMENT_METHODS: "/payment-methods",
  PAYMENT_METHODS_ADD: "/payment-methods/add",
  PAYMENT_METHODS_EDIT: (id: string | number) => `/payment-methods/${id}/edit`,
  INVOICE_STATUSES: "/invoice-statuses",
  INVOICE_STATUSES_ADD: "/invoice-statuses/add",
  INVOICE_STATUSES_EDIT: (id: string | number) =>
    `/invoice-statuses/${id}/edit`,
  INVOICES: "/invoices",
  INVOICES_ADD: "/invoices/add",
  INVOICES_ADD_BY_APPOINTMENT: "/invoices/add-by-appointment",
  INVOICES_EDIT: (id: string | number) => `/invoices/${id}/edit`,
  INVOICES_DETAILS: (id: string | number) => `/invoices/${id}`,
  INVOICES_EDIT_ITEMS: (id: string | number) => `/invoices/${id}/edit-items`,
  INVOICES_EDIT_BUYER: (id: string | number) => `/invoices/${id}/edit-buyer`,
  DOCTOR: {
    PATIENTS: "/doctor/patients",
    APPOINTMENTS: "/doctor/appointments",
    APPOINTMENTS_DETAILS: (id: string | number) =>
      `/doctor/appointments/${id}/details`,
  },
  PATIENT: {
    PROFILE: "/patient/profile",
    SCHEDULE: "/patient/schedule",
    APPOINTMENTS_DETAILS: (id: string | number) =>
      `/patient/appointments/details/${id}`,
  },
} as const;
